import { v4 as uuidv4 } from 'uuid';

import { ammountBord, OptionRoulette } from './types';
export const dummyAvatarIcon =
  'https://static.vecteezy.com/system/resources/previews/007/319/933/non_2x/black-avatar-person-icons-user-profile-icon-vector.jpg';

export const months = [
  'Styczeń',
  'Luty',
  'Marzec',
  'Kwiecień',
  'Maj',
  'Czerwiec',
  'Lipiec',
  'Sierpień',
  'Wrzesień',
  'Październik',
  'Listopad',
  'Grudzień',
];

export const days: string[] = [
  'Poniedziałek',
  'Wtorek',
  'Środa',
  'Czwartek',
  'Piątek',
  'Sobota',
  'Niedziela',
];
export const indexNum: number = 1;
export const variant2000: ammountBord[] = [
  { id: uuidv4(), isCrossOut: false, value: 30 },
  { id: uuidv4(), isCrossOut: false, value: 110 },
  { id: uuidv4(), isCrossOut: false, value: 24 },
  { id: uuidv4(), isCrossOut: false, value: 47 },
  { id: uuidv4(), isCrossOut: false, value: 55 },
  { id: uuidv4(), isCrossOut: false, value: 10 },
  { id: uuidv4(), isCrossOut: false, value: 82 },
  { id: uuidv4(), isCrossOut: false, value: 25 },
  { id: uuidv4(), isCrossOut: false, value: 65 },
  { id: uuidv4(), isCrossOut: false, value: 120 },
  { id: uuidv4(), isCrossOut: false, value: 23 },
  { id: uuidv4(), isCrossOut: false, value: 53 },
  { id: uuidv4(), isCrossOut: false, value: 15 },
  { id: uuidv4(), isCrossOut: false, value: 90 },
  { id: uuidv4(), isCrossOut: false, value: 34 },
  { id: uuidv4(), isCrossOut: false, value: 61 },
  { id: uuidv4(), isCrossOut: false, value: 70 },
  { id: uuidv4(), isCrossOut: false, value: 100 },
  { id: uuidv4(), isCrossOut: false, value: 42 },
  { id: uuidv4(), isCrossOut: false, value: 50 },
  { id: uuidv4(), isCrossOut: false, value: 74 },
  { id: uuidv4(), isCrossOut: false, value: 40 },
  { id: uuidv4(), isCrossOut: false, value: 77 },
  { id: uuidv4(), isCrossOut: false, value: 20 },
  { id: uuidv4(), isCrossOut: false, value: 95 },
  { id: uuidv4(), isCrossOut: false, value: 22 },
  { id: uuidv4(), isCrossOut: false, value: 85 },
  { id: uuidv4(), isCrossOut: false, value: 12 },
  { id: uuidv4(), isCrossOut: false, value: 80 },
  { id: uuidv4(), isCrossOut: false, value: 38 },
  { id: uuidv4(), isCrossOut: false, value: 60 },
  { id: uuidv4(), isCrossOut: false, value: 91 },
  { id: uuidv4(), isCrossOut: false, value: 200 },
];

// Poprawione variant3000 z sumą równą 3000
export const variant3000: ammountBord[] = [
  { id: uuidv4(), isCrossOut: false, value: 55 },
  { id: uuidv4(), isCrossOut: false, value: 150 },
  { id: uuidv4(), isCrossOut: false, value: 50 },
  { id: uuidv4(), isCrossOut: false, value: 85 },
  { id: uuidv4(), isCrossOut: false, value: 90 },
  { id: uuidv4(), isCrossOut: false, value: 35 },
  { id: uuidv4(), isCrossOut: false, value: 110 },
  { id: uuidv4(), isCrossOut: false, value: 40 },
  { id: uuidv4(), isCrossOut: false, value: 100 },
  { id: uuidv4(), isCrossOut: false, value: 160 },
  { id: uuidv4(), isCrossOut: false, value: 45 },
  { id: uuidv4(), isCrossOut: false, value: 80 },
  { id: uuidv4(), isCrossOut: false, value: 45 },
  { id: uuidv4(), isCrossOut: false, value: 120 },
  { id: uuidv4(), isCrossOut: false, value: 55 },
  { id: uuidv4(), isCrossOut: false, value: 90 },
  { id: uuidv4(), isCrossOut: false, value: 120 },
  { id: uuidv4(), isCrossOut: false, value: 130 },
  { id: uuidv4(), isCrossOut: false, value: 75 },
  { id: uuidv4(), isCrossOut: false, value: 85 },
  { id: uuidv4(), isCrossOut: false, value: 110 },
  { id: uuidv4(), isCrossOut: false, value: 80 },
  { id: uuidv4(), isCrossOut: false, value: 125 },
  { id: uuidv4(), isCrossOut: false, value: 55 },
  { id: uuidv4(), isCrossOut: false, value: 140 },
  { id: uuidv4(), isCrossOut: false, value: 50 },
  { id: uuidv4(), isCrossOut: false, value: 100 },
  { id: uuidv4(), isCrossOut: false, value: 30 },
  { id: uuidv4(), isCrossOut: false, value: 130 },
  { id: uuidv4(), isCrossOut: false, value: 60 },
  { id: uuidv4(), isCrossOut: false, value: 90 },
  { id: uuidv4(), isCrossOut: false, value: 150 },
  { id: uuidv4(), isCrossOut: false, value: 160 },
];

// Poprawione variant4000 z sumą równą 4000
export const variant4000: ammountBord[] = [
  { id: uuidv4(), isCrossOut: false, value: 100 },
  { id: uuidv4(), isCrossOut: false, value: 160 },
  { id: uuidv4(), isCrossOut: false, value: 50 },
  { id: uuidv4(), isCrossOut: false, value: 100 },
  { id: uuidv4(), isCrossOut: false, value: 125 },
  { id: uuidv4(), isCrossOut: false, value: 50 },
  { id: uuidv4(), isCrossOut: false, value: 140 },
  { id: uuidv4(), isCrossOut: false, value: 100 },
  { id: uuidv4(), isCrossOut: false, value: 120 },
  { id: uuidv4(), isCrossOut: false, value: 200 },
  { id: uuidv4(), isCrossOut: false, value: 100 },
  { id: uuidv4(), isCrossOut: false, value: 90 },
  { id: uuidv4(), isCrossOut: false, value: 100 },
  { id: uuidv4(), isCrossOut: false, value: 150 },
  { id: uuidv4(), isCrossOut: false, value: 75 },
  { id: uuidv4(), isCrossOut: false, value: 140 },
  { id: uuidv4(), isCrossOut: false, value: 160 },
  { id: uuidv4(), isCrossOut: false, value: 180 },
  { id: uuidv4(), isCrossOut: false, value: 90 },
  { id: uuidv4(), isCrossOut: false, value: 110 },
  { id: uuidv4(), isCrossOut: false, value: 150 },
  { id: uuidv4(), isCrossOut: false, value: 80 },
  { id: uuidv4(), isCrossOut: false, value: 160 },
  { id: uuidv4(), isCrossOut: false, value: 50 },
  { id: uuidv4(), isCrossOut: false, value: 170 },
  { id: uuidv4(), isCrossOut: false, value: 50 },
  { id: uuidv4(), isCrossOut: false, value: 130 },
  { id: uuidv4(), isCrossOut: false, value: 85 },
  { id: uuidv4(), isCrossOut: false, value: 150 },
  { id: uuidv4(), isCrossOut: false, value: 85 },
  { id: uuidv4(), isCrossOut: false, value: 150 },
  { id: uuidv4(), isCrossOut: false, value: 200 },
  { id: uuidv4(), isCrossOut: false, value: 200 },
];

export const rouletteAmount: OptionRoulette[] = [
  { option: '1' },
  { option: '2' },
  { option: '5' },
  { option: '10' },
  { option: '15' },
  { option: '20' },
  { option: '30' },
  { option: '50' },
  { option: '100' },
];

